### PR TITLE
feat: make uploadsLimit into  user setting

### PR DESCRIPTION
**Pull request by gdy666**
QQ截图20240507222301

### CODE REVIEW

**Comment by o1egl** [comment]
This PR adds only a client-side naive approach, which can be easily overridden. The proper approach requires server-side implementation as well. Why do we need it in general?

**Comment by gdy666** [comment]
> This PR adds only a client-side naive approach, which can be easily overridden. The proper approach requires server-side implementation as well. Why do we need it in general?

The intention of this PR is solely to allow the client to control the number of concurrent file uploads, as in real-world applications, when clients upload files concurrently, upload speed may significantly decrease compared to uploading a single file due to factors such as concurrent disk reads or other performance issues.

**Comment by gdy666** [comment]
> This PR adds only a client-side naive approach, which can be easily overridden. The proper approach requires server-side implementation as well. Why do we need it in general?

By the way, when uploading concurrently, what is displayed here is just the average upload speed. Shouldn't it display the total upload speed instead?

**Comment by Caian** [comment]
I like this idea very much. I usually update large files to my server, so it is better to have a few files ready versus a lot of files on the fly.

Being a quality-of-life feature for a particular user it is not a problem that it is not enforced on the server-side.

**Pull request closed without merging**
