### PR TITLE
feat: add upload file list with progress

### PR DESCRIPTION
**Pull request by filippofinke**
**Description**
Add the list of files that are being uploaded and their relative progress.

Reference to issue #1380

out

### CODE REVIEW

**Comment by ramiresviana** [comment]
While it looks functional, the design is in a rough state and needs improvement. The progress indicator takes up a large part or even all of the screen space, depending on the number of files being uploaded. We need a compact design that doesn't get in the way of users and fits different screen sizes.

**Comment by o1egl** [comment]
I'd suggest something like that one https://github.com/filebrowser/filebrowser/issues/1380#issuecomment-825607117 . Ideally, this window should be minimized and expanded when the user clicks on it

**Comment by filippofinke** [comment]
> I'd suggest something like that one [#1380 (comment)](https://github.com/filebrowser/filebrowser/issues/1380#issuecomment-825607117) . Ideally, this window should be minimized and expanded when the user clicks on it

Thank you for the feedback.

I'll work on it as soon as I have time.

**Comment by filippofinke** [comment]
@ramiresviana @o1egl 

I have updated the design, still some work has to be done.

out




It's giving errors because my server disk is full.

**Comment by ramiresviana** [comment]
Please make sure that you're using the project ESLint rules, making the style of your code consistent with the current codebase.

When there's a upload in progress, users cannot upload more files since the header action shows only the progress prompt.

**Comment by filippofinke** [comment]
> Please make sure that you're using the project ESLint rules, making the style of your code consistent with the current codebase.
> 
> When there's a upload in progress, users cannot upload more files since the header action shows only the progress prompt.

I have fixed the code style. 

I agree that users can't upload more files because of the progress prompt.

I'll try to create a prompt on the bottom right that doesn't block user navigation and that can be maximized/minimized.

Something like this one:

image

**Comment by filippofinke** [comment]
I am currently working on the icons on the left side of the file name, some other designs improvement and then I'll do some refactoring.

Current status:
out

**Comment by filippofinke** [comment]
Added icons:

image

**Pull request merged**
