### PR TITLE
i18n: zh: minor fix

### PR DESCRIPTION
**Pull request by Equim-chan**

### CODE REVIEW

**Comment by hacdias** [comment]
Thank you @Equim-chan! 😄

**Comment by Equim-chan** [comment]
By the way, I'm improving the download handler at the moment. Another PR may drop soon.

**Comment by hacdias** [comment]
Sure! Thank you @Equim-chan! 😄 It just must not put everything on RAM as I did before 😅

**Comment by Equim-chan** [comment]
Haha, actually that fix is exactly what makes a new problem.

**Pull request merged**
