### PR TITLE
Create m3u playlist by selecting files.

### PR DESCRIPTION
**Pull request by g45t345rt**
**Description**
Select video or audio files and click the playlist icon in the header bar.
The program will create a playlist.m3u file and save to the desktop without having to request the server.
You can start watching videos or listening to audio by opening the playlist.m3u with VLC.

**Why**
Avoid copy and paste the raw link address every time you want to open the file in VLC.
Avoid downloading the entire file before opening in VLC.

_Related with_
https://github.com/filebrowser/filebrowser/issues/745
https://github.com/filebrowser/filebrowser/issues/749
https://github.com/zoidy/filebrowser-streamlink/

### CODE REVIEW

**Comment by o1egl** [comment]
To access the file, the auth token must be provided. So creating a file with hardcoded links is not the right solution. Also, before merging this type of functionality, we need to be sure that it is in high demand.

**Comment by zoidy** [comment]
This functionality is very useful for me. I ended up implementing it via the backend for better robustness. By doing it this way, it's possible to create playlists of entire directory trees and avoids any auth issues by creating shared links in the backend directly.  You can see the changes in my fork https://github.com/zoidy/filebrowser  ~~The fork is currently out of date from upstream but I will update it~~ fork updated

**Comment by methatronc** [comment]
> 
> 
> To access the file, the auth token must be provided. So creating a file with hardcoded links is not the right solution. Also, before merging this type of functionality, we need to be sure that it is in high demand.

If that could be of any help, I second that request : I focus on optimizing resources on a light server and being able to share terabits of data without encoding them with the only client-requirement of installing vlc would be quite awesome !

**Comment by snvoid** [comment]
This would a great to have so hopefully it gets implemented.

**Comment by xiaole51** [comment]
This is a very needed function, batch exporting and sharing links should be realized, at least with CLI.

**Pull request closed without merging**
