### PR TITLE
Invitation code

### LINKED ISSUE #1710: Invitation code for registration
It‘s possible to add a invitation code for registration? 

Adminstrator can set a invitation code in Global Settings, then only people have this code can regist successfully.

This feature is quite useful for registration.

Thanks!

### PR DESCRIPTION
**Pull request by niubility000**
fixed: #1710

And when "allow users to signup" is selected, but "use invitation code" is not selected, the invitation code input box will be hidden in the signup page.

### CODE REVIEW

**Comment by o1egl** [comment]
I think it should be possible to create multiple unique invitation codes

**Comment by niubility000** [comment]
> I think it should be possible to create multiple unique invitation codes

Done!
Just use ; to separate multiple unique invitation codes, and use 
                if !strings.Contains(";"+d.InvitationCode+";", ";"+info.InvitationCode+";"){
to compare them.

**Comment by o1egl** [comment]
> > I think it should be possible to create multiple unique invitation codes
> 
> Done! Just use ; to separate multiple unique invitation codes, and use if !strings.Contains(";"+d.InvitationCode+";", ";"+info.InvitationCode+";"){ to compare them.

This is not exactly what I had in mind. I think it is better to have a list similar to the shares and have an object in the database that indicates if the code is active or not and which user was registered with it.

**Comment by niubility000** [comment]
If the code is active, other visitors can't use it any more to sign up? That's unique.
It's a little bit more complicated.

**Comment by adrium** [comment]
Honestly having so many commits with the message _"Add files via upload"_ makes it hard to review the code. Being a feature integrated into the authentication system, I think the code changes should be well structured, semantically grouped, and with good commit messages.

**Comment by niubility000** [comment]
> Honestly having so many commits with the message _"Add files via upload"_ makes it hard to review the code. Being a feature integrated into the authentication system, I think the code changes should be well structured, semantically grouped, and with good commit messages.

I can only visit github using browser through a web proxy. I need to upload and commit the files one by one. That's why there are so many commits and they are not grouped. You can just review the 'files changed' section.  
Next time I will write commit messages.
And I am not a professional programmer.  So feel free to modify them or make a new PR.

**Pull request closed without merging**
