### PR TITLE
open all the pdf files correctly

### LINKED ISSUE #1442: PDFs are opened as text files
**Description**
When opening a PDF from File Browser, it sometimes opens as a text file in the editor. It happens around half of the times I try to open a PDF. If I download the PDF, it opens just fine in Adobe Acrobat, Chrome and Edge.

**Expected behaviour**
I should be able to see the PDF.

**What is happening instead?**
image
 
Tested with lots of PDFs and two File Browser versions (a 1 year-old installation and the new v2.15.0). Same behavior on Chrome for Windows, Chrome for Android and Safari on iPhone.

### PR DESCRIPTION
**Pull request by niubility000**
fixed: #1442
test with this sample pdf file:
[scan_2021-06-21.13.38.42.pdf](https://github.com/filebrowser/filebrowser/files/7778138/scan_2021-06-21.13.38.42.pdf)

before: 

after:

I also changed the icon for pdf files, make it easier to identify.
before:

after:

### CODE REVIEW

**Comment by niubility000** [comment]
BTW, is there something wrong with commitlint?

**Comment by mckaygerhard** [comment]
please @o1egl  ..   the commits are not so xplanatory but THANKS TO @niubility000 THIS LONG LONG PROBLEM IS SOLVED; ALREADY TESTED!

**Comment by mckaygerhard** [comment]
@Teraskull it seesm you also can merge this commit? if the authors of this project do not have time please can @o1egl  delegate a person to manage at least the issues?

**Comment by Teraskull** [comment]
@mckaygerhard Sorry, no, I don't have merge perms.

**Pull request merged**
