### PR TITLE
Migration to Vue 3

### PR DESCRIPTION
**Pull request by kloon15**
Brings the frontend to run under Vue 3 while maintaining the same behavior as much as possible.
Current status: rewrite to typescript and compositions API mostly finished.

:rotating_light: Before submitting your PR, please read [community](https://github.com/filebrowser/community), and indicate which issues (in any of the repos) are either fixed or closed by this PR. See [GitHub Help: Closing issues using keywords](https://help.github.com/articles/closing-issues-via-commit-messages/).

- [x] DO make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your master!
- [x] DO make sure you are making a pull request against the **master branch** (left side). Also you should start *your branch* off *our master*.
- [x] DO make sure that File Browser can be successfully built. See [builds](https://github.com/filebrowser/community/blob/master/builds.md) and [development](https://github.com/filebrowser/community/blob/master/development.md).
- [x] DO make sure that related issues are opened in other repositories. I.e., the frontend, caddy plugins or the web page need to be updated accordingly.
- [x] AVOID breaking the continuous integration build.

### CODE REVIEW

**Comment by kloon15** [comment]
Implements #2623

**Comment by joepbuhre** [comment]
I like it and I want to perhaps join in on this. But what is the plan / to do list. Also do we want to perhaps consider moving to typescript (improved tooling). Let me know how I can join in

**Comment by kloon15** [comment]
> I like it and I want to perhaps join in on this. But what is the plan / to do list. Also do we want to perhaps consider moving to typescript (improved tooling). Let me know how I can join in

Thanks for ur interest, my current plan for this migration is to port the current codebase to Vue3 with only mostly necessary changes before we reach the EOL of Vue2.
I would absolutely love if someone took the time and effort to rewrite it with typescript and compositions API but that is out of my scope atm. Im also not very familiar at all with Vue.

The tasks left on my todo list are:
- Sync with master branch
- Replace noty with something that is still supported/maintained
- Fix lint warnings

Ur more than welcome to help out in any of those tasks or lmk if u find anything that seems wrong.

**Comment by joepbuhre** [comment]
Okay good to know. I'll build upon your branch and try to move everything over to composition api and typescript. Lovely to hear that almost everything is ported to Vue3.

**Comment by joepbuhre** [comment]
Just checked about noty. I almost exclusively use my own notification system using just pinia. Will try to make a semi compatible port from noty :D

**Comment by kloon15** [comment]
> Just checked about noty. I almost exclusively use my own notification system using just pinia. Will try to make a semi compatible port from noty :D

I just looked into this and found vue-toastification to have everything we need and added it so u dont have to bother with this.
Quick question if u know: why couldnt i use $t inside the custom toast component?

**Comment by joepbuhre** [comment]
Ah okay great no problem. Less work for me. I have worked the last few hours to get everything ported to Typescript. At least all the *.js files are ts files right now, next steps are going to be converting the vue files

**Comment by joepbuhre** [comment]
I don't know how to contribute to this specific pull request so that's one thing. My code resides here for now: https://github.com/joepbuhre/filebrowser/tree/vue3

**Comment by kloon15** [comment]
> I don't know how to contribute to this specific pull request so that's one thing. My code resides here for now: https://github.com/joepbuhre/filebrowser/tree/vue3

Great job so far, how long do u reckon it would take to convert the vue files to composition API? Ideally i would like to have this PR merged soon, so ppl with existing/new PRs can adopt to Vue 3.
Also just nitpicking but could we please use PascalCase for Typescript types?

**Comment by joepbuhre** [comment]
I am going to try to get everything sorted by the end of this weekend. Should be fairly easy.

Regarding typescript types. They could still be much improved. I am not quite sure about the backend types and which what requires. For example filebrowser uses sometimes file, but `File` is a reserved type. 
Do we want to prefix everything with `FF` or `Filebrowser`?

**Comment by kloon15** [comment]
> I am going to try to get everything sorted by the end of this weekend. Should be fairly easy.
> 
> Regarding typescript types. They could still be much improved. I am not quite sure about the backend types and which what requires. For example filebrowser uses sometimes file, but `File` is a reserved type. Do we want to prefix everything with `FF` or `Filebrowser`?

I usually prefix mine with I (as in interface), esp if its data coming from an API or smth. Ur guess is as good as mine, if u want i can take a look at the Go data structs and figure some out.

**Comment by joepbuhre** [comment]
> > I am going to try to get everything sorted by the end of this weekend. Should be fairly easy.
> > Regarding typescript types. They could still be much improved. I am not quite sure about the backend types and which what requires. For example filebrowser uses sometimes file, but `File` is a reserved type. Do we want to prefix everything with `FF` or `Filebrowser`?
> 
> I usually prefix mine with I (as in interface), esp if its data coming from an API or smth. Ur guess is as good as mine, if u want i can take a look at the Go data structs and figure some out.

Hm okay. I'll check it out. Thanks for the input

**Comment by joepbuhre** [comment]
New update! I have converted all root views to Typescript / Composition API. So that's all sorted. Now the components and other views. 

Also please check my Dockerfile. I have rewritten it to build everything from within the Dockerfile, this leads to better and more expected / reproducible builds

**Comment by kloon15** [comment]
> New update! I have converted all root views to Typescript / Composition API. So that's all sorted. Now the components and other views.
> 
> Also please check my Dockerfile. I have rewritten it to build everything from within the Dockerfile, this leads to better and more expected / reproducible builds

Cool!
Yea i use a custom Dockerfile aswell, but read this: [https://github.com/filebrowser/filebrowser/pull/2614#issuecomment-1665692445](https://github.com/filebrowser/filebrowser/pull/2614#issuecomment-1665692445)

**Comment by joepbuhre** [comment]
> Cool! Yea i use a custom Dockerfile aswell, but read this: [#2614 (comment)](https://github.com/filebrowser/filebrowser/pull/2614#issuecomment-1665692445)

Ahh good to know! Will drop my custom Dockerfile from the repo then. As you'd probably know, my go knowledge is not yet very up to par with my Vue / TS knowledge :D

**Comment by joepbuhre** [comment]
8 views down, 7 views & all the components to go! It's quite a challenge but I am making my way...

**Comment by kloon15** [comment]
> 8 views down, 7 views & all the components to go! It's quite a challenge but I am making my way...

Coming along nicely, I merged ur current commits and added explicit type imports so eslint wont freak out anymore.

**Comment by joepbuhre** [comment]
Great. I do have two branches Vue3 + vue3-wip. Vue3-wip is inbetween and Vue3 is my latest

**Comment by joepbuhre** [comment]
Okay wrote all views except the files/* views to composition api & typescript. Thos are quite large. Everything is pushed to this branch https://github.com/joepbuhre/filebrowser/tree/vue3. 
Will merge your changes into my branch asap.  In multiple spots I've put in `// @ts-ignore` to not break current flow. If this can be fixed or changed that would be awesome.

**Comment by kloon15** [comment]
> Great. I do have two branches Vue3 + vue3-wip. Vue3-wip is inbetween and Vue3 is my latest

Im merging ur vue3 branch, i just called it vue3-wip for my local branch.

**Comment by joepbuhre** [comment]
I am currently checking the way to import types. I usually don't use them unless I specifically have to eg: importing types from another library in a monorepo. I want to avoid this kind of behaviour if it's possible. This is also been discussed in the official typescript repo (https://github.com/microsoft/TypeScript/issues/39861#issuecomment-668131921).

I checked all the files and removed import types where it was being used. Also fixed a bunch of type errors Otherwise it looks super great.

**Comment by kloon15** [comment]
> I am currently checking the way to import types. I usually don't use them unless I specifically have to eg: importing types from another library in a monorepo. I want to avoid this kind of behaviour if it's possible. This is also been discussed in the official typescript repo ([microsoft/TypeScript#39861 (comment)](https://github.com/microsoft/TypeScript/issues/39861#issuecomment-668131921)).
> 
> I checked all the files and removed import types where it was being used. Also fixed a bunch of type errors Otherwise it looks super great.

Well idk about how auto import works and neither does eslint apparently. U can remove the type keyword i dont mind, but we should definitely keep the imports for cases like this. I always prefer to be explicit.

**Comment by joepbuhre** [comment]
So the auto import actually is something the Vite builder will do out of itselves, that is the Typescript bundler. 
I also looked more into the issue of eslint and the guys from eslint are saying disabling the actual no-undef rule: https://typescript-eslint.io/linting/troubleshooting/#i-get-errors-from-the-no-undef-rule-about-global-variables-not-being-defined-even-though-there-are-no-typescript-errors

Furthermore I prefer the bundler imports because that seems to be the way SPA's are being developed, however I can't find anything in one of the other direction. So I think it's going to be a choice we have to make. 

For now you can just pull my branche, check my eslint config, there aren't any major eslint errors (just the props mutation) and typescript is also totally fine. 

If this isn't the road we want to go it's also okay then we can go forward from you latest commits. Let me know as you have been with the project earlier

**Comment by kloon15** [comment]
> So the auto import actually is something the Vite builder will do out of itselves, that is the Typescript bundler. I also looked more into the issue of eslint and the guys from eslint are saying disabling the actual no-undef rule: https://typescript-eslint.io/linting/troubleshooting/#i-get-errors-from-the-no-undef-rule-about-global-variables-not-being-defined-even-though-there-are-no-typescript-errors
> 
> Furthermore I prefer the bundler imports because that seems to be the way SPA's are being developed, however I can't find anything in one of the other direction. So I think it's going to be a choice we have to make.
> 
> For now you can just pull my branche, check my eslint config, there aren't any major eslint errors (just the props mutation) and typescript is also totally fine.
> 
> If this isn't the road we want to go it's also okay then we can go forward from you latest commits. Let me know as you have been with the project earlier

Sure, I'm cool with that, seems like VSCode can find the types aswell which i had an issue with before. I will merge ur branch, good job!

**Comment by kloon15** [comment]
@joepbuhre Is there anything i should look at in the new code? I fixed all the ts-ignore code that i found.
I did find some random commented out code that was needed, should i check for more?

**Comment by joepbuhre** [comment]
@kloon15 nice. Love the way it's going. To answer your question, the latest commits of mine were just Typescript related. I also fixed the user-form erorr by creating a extra user type, where all the fields are optional. 
Going forward it's just converting the components, maybe updating some stuff and then we're going fast to the endline!
Will probably have some time Thursday to work on converting the components.

**Comment by joepbuhre** [comment]
@kloon15 just checked a your commits. They look quite nicely. Indeed my way of working is converting everything to TS + Composition API and ignoring some errors to adhere to the original Javascript flow. Don't want to change too much of that at once, only if absolutely required. Sometimes there should be indeed some commented out lines removed. The time I am working on this through the week is from 22:00 - 01:00 so apologies for some of my comments that are still there. 🙃

**Comment by kloon15** [comment]
> @kloon15 just checked a your commits. They look quite nicely. Indeed my way of working is converting everything to TS + Composition API and ignoring some errors to adhere to the original Javascript flow. Don't want to change too much of that at once, only if absolutely required. Sometimes there should be indeed some commented out lines removed. The time I am working on this through the week is from 22:00 - 01:00 so apologies for some of my comments that are still there. 🙃

Yea thats perfectly fine, just drop a TODO comment where u think it doesnt look good or should be looked at later.

**Comment by joepbuhre** [comment]
Great. I will have some time from Sunday again to make a big dent in the conversion. Am on a quick getaway this weekend.

Will drop the TODOs if necessary, thanks :D

**Comment by axriosn** [comment]
You two have done some great work on this so far! I'd love to help out if you need it, just let me know what I can do.

**Comment by kloon15** [comment]
> You two have done some great work on this so far! I'd love to help out if you need it, just let me know what I can do.

Thank you, I could certainly appreciate if u could merge the upstream commits so we wont have conflicts. I didnt have much free time lately.
Also im not sure how much work @joepbuhre has left and if he needs any help with that.

**Comment by joepbuhre** [comment]
Hi @axriosn & @kloon15,

Just done with all the views. Next step up are the components. So perhaps you can start converting some of the components. I am hoping I will have an afternoon in this weekend so I can push through all the components.
Next steps after this we will need to start prepping to merge this into live.

**Comment by joepbuhre** [comment]
Or better yet @axriosn. Indeed if you can merge the upstream features into this branch that would be great.

**Comment by joepbuhre** [comment]
I had some time today and hopefully some more this weekend. But I've made some additions

**Comment by kloon15** [comment]
> I had some time today and hopefully some more this weekend. But I've made some additions

Cool! Do u have any idea why v-focus doesnt have any effect? Its called but no focus is given to the component.

**Comment by joepbuhre** [comment]
> > I had some time today and hopefully some more this weekend. But I've made some additions
> 
> Cool! Do u have any idea why v-focus doesnt have any effect? Its called but no focus is given to the component.

Can you point to the code what you mean? Can't seem to reproduce it

**Comment by kloon15** [comment]
> > > I had some time today and hopefully some more this weekend. But I've made some additions
> > 
> > 
> > Cool! Do u have any idea why v-focus doesnt have any effect? Its called but no focus is given to the component.
> 
> Can you point to the code what you mean? Can't seem to reproduce it

Click on new folder/file and it should focus the input but it doesnt for me.

**Comment by kloon15** [comment]
@joepbuhre How much conversion do we have left? I was sick on and off i couldnt do much lately but i was fixing up the prompts.

**Comment by omalk98** [comment]
> > I had some time today and hopefully some more this weekend. But I've made some additions
> 
> Cool! Do u have any idea why v-focus doesnt have any effect? Its called but no focus is given to the component.

I have a fix for this, it seems to have a general issue with v-focus on any type of input other than `type="number"`.
I'm working on a PR addressing multiple small issues with the frontend + adding context menu. I would be open to moving those fixes to this repo in hopes to have a better Vue3 upgrade.

**Comment by kloon15** [comment]
> > > I had some time today and hopefully some more this weekend. But I've made some additions
> > 
> > 
> > Cool! Do u have any idea why v-focus doesnt have any effect? Its called but no focus is given to the component.
> 
> I have a fix for this, it seems to have a general issue with v-focus on any type of input other than `type="number"`. I'm working on a PR addressing multiple small issues with the frontend + adding context menu. I would be open to moving those fixes to this repo in hopes to have a better Vue3 upgrade.

Thanks i figured out it was the css animation property messing up the focus. Anyway i replaced them with a proper modal implementation that has focus-trap built in. The only thing thats not being focused is the share dialog cus its conditional but i couldnt figure out how to delay the focus.
Sure im gladly accepting PRs or fixes, i myself dont have much time with xmas around.

**Comment by omalk98** [comment]
I have a bit of time till Friday, I'll work on converting the new features and fixes from master.

**Comment by kloon15** [comment]
> I have a bit of time till Friday, I'll work on converting the new features and fixes from master.

Did u make any progress?

**Comment by omalk98** [comment]
> > I have a bit of time till Friday, I'll work on converting the new features and fixes from master.
> 
> 
> 
> Did u make any progress?

Yes, I've managed to merge most of the changes from master, I will update my PR sometime this week to your repo @kloon15 . just noticed I pushed 2 commits that aren't ready for production.

**Comment by niubility000** [comment]
Really thanks for the contribution. It's a huge job.

**Comment by niubility000** [comment]
Looking forwards to this update.

**Comment by kloon15** [comment]
> > > I have a bit of time till Friday, I'll work on converting the new features and fixes from master.
> > 
> > 
> > Did u make any progress?
> 
> Yes, I've managed to merge most of the changes from master, I will update my PR sometime this week to your repo @kloon15 . just noticed I pushed 2 commits that aren't ready for production.

Hey, any progress? If u couldnt finish it thats fine, just open a PR against my branch and we will figure it out.

**Comment by omalk98** [comment]
> Hey, any progress? If u couldnt finish it thats fine, just open a PR against my branch and we will figure it out.

Let me give it another shot this week, I've unfortunately gotten overwhelmed with some things and didn't get a chance to work on it. 
If not the PR is already open and u can feel free to modify/merge it whenever. 

https://github.com/kloon15/filebrowser/pull/1

**Comment by omalk98** [comment]
@kloon15 Branch is now aligned with master again, I pulled the most recent updates as well and should be ready for merge.

**Comment by kloon15** [comment]
> @kloon15 Branch is now aligned with master again, I pulled the most recent updates as well and should be ready for merge.

Thank you very much i will test it this week!

**Comment by omalk98** [comment]
@kloon15 I've done some light testing and there seems to be a bug with the prompts. For (`Copy`, `Move`, `Upload`) prompts.
The issue:
When uploading/copying/moving a file with a duplicate causing a conflict, the prompt shows up momentarily before being popped from `currentPrompt` array and being unable to reach it. Seems to exist before the merge.
How to reproduce: 
Copy/Move/Upload a duplicate file into FileBrowser.

I suspect this is due to Pinia running state mutations async but not confirmed yet.

**Comment by kloon15** [comment]
> @kloon15 I've done some light testing and there seems to be a bug with the prompts. For (`Copy`, `Move`, `Upload`) prompts. The issue: When uploading/copying/moving a file with a duplicate causing a conflict, the prompt shows up momentarily before being popped from `currentPrompt` array and being unable to reach it. Seems to exist before the merge. How to reproduce: Copy/Move/Upload a duplicate file into FileBrowser.
> 
> I suspect this is due to Pinia running state mutations async but not confirmed yet.

I do get the prompt on Upload
image

**Comment by omalk98** [comment]
> > @kloon15 I've done some light testing and there seems to be a bug with the prompts. For (`Copy`, `Move`, `Upload`) prompts. The issue: When uploading/copying/moving a file with a duplicate causing a conflict, the prompt shows up momentarily before being popped from `currentPrompt` array and being unable to reach it. Seems to exist before the merge. How to reproduce: Copy/Move/Upload a duplicate file into FileBrowser.
> 
> > 
> 
> > I suspect this is due to Pinia running state mutations async but not confirmed yet.
> 
> 
> 
> I do get the prompt on Upload
> 
> image
> 
> 

Will test it further this weekend to confirm why it's happening on my side

**Comment by kloon15** [comment]
This looks good to me, ill change it to ready to review. Thanks everyone for their contribs!

**Comment by o1egl** [comment]
You all have done a great job!

**Comment by gdy666** [comment]
@kloon15 Hi,The Vue3 version is likely related to the code in the "VideoPlayer.vue" file, which cannot play MKV format video files.

**Comment by kloon15** [comment]
> @kloon15 Hi,The Vue3 version is likely related to the code in the "VideoPlayer.vue" file, which cannot play MKV format video files.

The thing is, most browsers dont even support the mkv container, let alone the proprietary codecs such files are encoded with.
> Modern web browsers only support the WebM container format that is based on Matroska, but limited to royalty-free codecs. Even when the MKV file contains media encoded by a codec that the browser is able to decode, most browsers are unable to play media in such a container.

Whats ur use case that requires u to play mkv in a browser?

**Comment by gdy666** [comment]
> > @kloon15 Hi,The Vue3 version is likely related to the code in the "VideoPlayer.vue" file, which cannot play MKV format video files.
> 
> The thing is, most browsers dont even support the mkv container, let alone the proprietary codecs such files are encoded with.
> 
> > Modern web browsers only support the WebM container format that is based on Matroska, but limited to royalty-free codecs. Even when the MKV file contains media encoded by a codec that the browser is able to decode, most browsers are unable to play media in such a container.
> 
> Whats ur use case that requires u to play mkv in a browser?

You can test this file, which could be played online in the previous version of the file browser.

https://www.daji.it:66/release/v2.5.1/test.mkv

Actually, what I mean is that all the MKV files I have been using could be played normally in the browser before.

**Comment by gdy666** [comment]
@kloon15 
Furthermore, when accessing FileBrowser with a non-local host, such as the internal IP 192.168.31.1, the copy function at this location is disabled.
QQ截图20240429092055

**Comment by gdy666** [comment]
Furthermore, when accessing FileBrowser with a non-local host (127.0.0.1/localhost), such as the internal IP 192.168.31.1, the copy function at this location is disabled (even though the link is shown as copied).

QQ截图20240429092055


QQ截图20240429113107

**Comment by kloon15** [comment]
> > > @kloon15 Hi,The Vue3 version is likely related to the code in the "VideoPlayer.vue" file, which cannot play MKV format video files.
> > 
> > 
> > The thing is, most browsers dont even support the mkv container, let alone the proprietary codecs such files are encoded with.
> > > Modern web browsers only support the WebM container format that is based on Matroska, but limited to royalty-free codecs. Even when the MKV file contains media encoded by a codec that the browser is able to decode, most browsers are unable to play media in such a container.
> > 
> > 
> > Whats ur use case that requires u to play mkv in a browser?
> 
> You can test this file, which could be played online in the previous version of the file browser.
> 
> https://www.daji.it:66/release/v2.5.1/test.mkv
> 
> Actually, what I mean is that all the MKV files I have been using could be played normally in the browser before.

We could bypass videojs for unsupported formats i guess. Dont have a better idea.

**Comment by Daniel-dev22** [comment]
This migration to vue3 broke the ability to pull down to refresh on mobile in a text editor.

https://github.com/filebrowser/filebrowser/issues/3131

I assume `@touchmove.prevent.stop` might be to blame.

**Pull request merged**
