### PR TITLE
Issue fix: Directory "others" execute permissions #300

### PR DESCRIPTION
**Pull request by ghost**
Fixed error access to inside the docker container.

### CODE REVIEW

**Comment by tokvv** [comment]
Issue fix: Directory "others" execute permissions #300
https://github.com/filebrowser/filebrowser/issues/300

**Comment by ghost** [comment]
Fixed error access to inside the docker container.

**Comment by eine** [comment]
@tokvv is changing from scratch to ubuntu compulsory? That seems to be a major change, not explicitly related to this issue. If so, we should probably discuss it in #300.

**Comment by ghost** [comment]
@1138-4EB It is not necessary to change from scratch to ubuntu. This is done in order to have access inside the container docker (there is not shell in scratch) and is not relevant to # 300. Maybe I need to make a new PR?

**Comment by eine** [comment]
@tokvv, yes, please. I agree that in some contexts it can be useful to have a shell available (e.g. 1138-4EB/hwd-ide). However, I think that choosing Ubuntu to be the only one is a strong decision.

On the one hand, if a single one is offered I'd go with either Alpine or Debían Buster Slim.

On the other hand, should we want to offer multiple ready-to-use images I'd extend #399 to provide five flavours: Scratch, Alpine, Debían, Ubuntu and Fedora. See http://travis-ci.com/1138-4EB/filebrowser

Anyway, I think that the most sensible approach is to provide the scratch version only and add an explanation in the docs about how to add file browser itself to any image with `COPY --from=filebrowser/filebrowser`. Or see https://github.com/1138-4EB/hwd-ide/blob/develop/filebrowser/Dockerfile

**Comment by salcedo** [comment]
Thank you for fixing the permissions issue. Is it possible to merge just that and move the discussion about switching from scratch to ubuntu elsewhere? I need the permissions fix ASAP.

**Comment by ghost** [comment]
@1138-4EB , good, i revert changes for Dockerfile. Can you merge this PR?
Thanks.

**Comment by eine** [comment]
@tokvv, thanks. Unfortunately, I don't have write permissions. Let's ping @hacdias and @Equim-chan.

**Comment by hacdias** [comment]
Thanks @tokvv

**Comment by hacdias** [comment]
I'll release a new minor/patch version of File Browser today with the latest bug fixes.

**Comment by salcedo** [comment]
:+1: @hacdias @tokvv

**Pull request merged**
