### PR TITLE
alternative ReCaptcha, close #366

### LINKED ISSUE #366: proposal: alternative ReCaptcha
Since nearly the whole Google is blocked in China, `https://www.google.com/recaptcha` is not an exception. However, `recaptcha.net` is [offical](https://s26.postimg.org/x735zdiyh/image.png) and [accessible from China](https://en.greatfire.org/https/recaptcha.net). Just change
```
https://www.google.com/recaptcha/api.js?render=explicit
```

to
```
https://recaptcha.net/recaptcha/api.js?render=explicit
```

in front end, and
```
https://www.google.com/recaptcha/api/siteverify
```

to
```
https://recaptcha.net/recaptcha/api/siteverify
```

in back end, and it should work as expected.

We may add an option, `alternative_recaptcha` in Caddy plugin, `--alternative-recaptcha` in CLI, to switch to `recaptcha.net` from `www.google.com` as host in both recaptcha handling (backend) and serving (frontend).

### PR DESCRIPTION
**Pull request by Equim-chan**
See #366.

Sub-PRs:
* https://github.com/filebrowser/frontend/pull/3
* https://github.com/filebrowser/filebrowser.github.io/pull/2

### CODE REVIEW

**Comment by Equim-chan** [comment]
Done, and proven to be working.

image

**Comment by Equim-chan** [comment]
Just a bit off-topic though, I don't know whether I should feel happy or sad that we, and many other fellows, have to make so many extra efforts for those who are not yet able to embrace the freedom that they deserve.

**Review by hacdias — APPROVED** [review]

**Comment by hacdias** [comment]
Thanks for this @Equim-chan 😄 This is awesome eheh

**Comment by hacdias** [comment]
@Equim-chan I know I've just merged this, but I'd like to ask you to change the option 'alternative_recaptcha' to 'recaptcha_host' so it is more direct. And do the same on https://github.com/filebrowser/filebrowser.github.io/pull/2 😺

**Comment by Equim-chan** [comment]
I don't really agree. `--recaptcha_host recaptcha.net` is longer than `--alternative-captcha`, and requires more parsing that is likely to fail if the user passes an invalid recaptcha host. The possible valid values are only `www.google.com` and `recaptcha.net`, so we can just use a boolean. recaptcha.net is also not very known.

**Comment by hacdias** [comment]
Oh okay. I thought there would be more alternatives

**Comment by sainiaj** [comment]
https://github.com/filebrowser/filebrowser/issues/3697
@Equim-chan can you please help me i keep getting the error message - unknown flag

**Pull request merged**
