### PR TITLE
feat: Add context menu for file listing

### PR DESCRIPTION
**Pull request by omalk98**
## Description

Added context menu on right click. Maps directly to all addressable header bar actions.

### Context Menu Features
- 1-to-1 mapping of the header bar actions except (toggle shell, switch view, select multiple)
- Double right-click to cancel custom context menu callback and trigger default browser context-menu
- Container aware (will not overflow outside screen bounds when opened by the bottom right corner of screen)

### Context Menu States:

**Single File:**
image

**Multiple Files**
image

**No File:**
image

### Reasons to Merge
Long requested feature, has been referenced in the following issues:

[#512 ](https://github.com/filebrowser/filebrowser/issues/512)
[#752 ](https://github.com/filebrowser/filebrowser/issues/752)
[#1031 ](https://github.com/filebrowser/filebrowser/discussions/1031)
[#1276 ](https://github.com/filebrowser/filebrowser/issues/1276)
[#1782 ](https://github.com/filebrowser/filebrowser/issues/1782)
[#2609 ](https://github.com/filebrowser/filebrowser/issues/2609)

:rotating_light: Before submitting your PR, please read [community](https://github.com/filebrowser/community), and indicate which issues (in any of the repos) are either fixed or closed by this PR. See [GitHub Help: Closing issues using keywords](https://help.github.com/articles/closing-issues-via-commit-messages/).

- [x] DO make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your master!
- [x] DO make sure you are making a pull request against the **master branch** (left side). Also you should start *your branch* off *our master*.
- [x] DO make sure that File Browser can be successfully built. See [builds](https://github.com/filebrowser/community/blob/master/builds.md) and [development](https://github.com/filebrowser/community/blob/master/development.md).
- [x] DO make sure that related issues are opened in other repositories. I.e., the frontend, caddy plugins or the web page need to be updated accordingly.
- [x] AVOID breaking the continuous integration build.

### CODE REVIEW

**Comment by omalk98** [comment]
Bump

**Comment by omalk98** [comment]
Bump

**Comment by o1egl** [comment]
Can you please merge the latest master and resolve conflicts?

**Comment by omalk98** [comment]
> Can you please merge the latest master and resolve conflicts? 

Will do, I'll get on to it sometime early May.

**Comment by omalk98** [comment]
Bump, will be working on an update to vue3 soon

**Pull request closed without merging**
