### PR TITLE
feat: remain in the same position when back from a subfolder

### PR DESCRIPTION
**Pull request by niubility000**
This is a update of #3052
When you return back from a subfolder, you will stay in the last position of the list. And the dir you entered before will be highlighted in PC. 
 

(I also formated the file using latest .eslintrc.json)

By the way, the commit message's format is so strict. The subject should start with fix:, and fix: can't be Fix:, and the subject should not end with a ".",  and the optional box should keep empty.  
Otherwise, we need to re-pull the whole request.

### CODE REVIEW

**Comment by alanmilinovic** [comment]
Using this for a while and it works perfectly.

**Comment by alanmilinovic** [comment]
Can this be merged and pushed to the next release please?

**Comment by o1egl** [comment]
There are some merge conflicts

**Comment by alanmilinovic** [comment]
@niubility000 can you please resolve merge conflicts?

**Pull request closed without merging**
