### PR TITLE
添加unzip按钮和后端相关实现，已支持权限相关逻辑

### PR DESCRIPTION
**Pull request by t924417424**
**Description**
为项目前端添加.zip、.bz2、.br、.tbz2、.gz、.xz、.rar、.tar等类型文件被选中时的unzip按钮，支持管理员后台进行unzip权限配置。
项目后端Permissions加入Unzip字段，用于增加unzip功能权限管理。

### CODE REVIEW

**Comment by ashesofdream** [comment]
大佬考虑支持7z文件吗

**Comment by gingerbeardman** [comment]
Translation:

> # Added unzip button and back-end related implementation, already supports permission related logic
> 
> ## Description
> 
> Add unzip buttons for the front end of the project when .zip, .bz2, .br, .tbz2, .gz, .xz, .rar, .tar and other file types are selected, and support unzip permission configuration in the admin backend.
> 
> Unzip field added to Permissions on the back end of the project for additional unzip permission management.

**Comment by gingerbeardman** [comment]
Looks good to me.

Only minor issue I see is that additional translations would be required, as this only includes English and Chinese (two types).

Nice work @t924417424 ! 🙌

Any thoughts @o1egl ?

**Comment by gingerbeardman** [comment]
That bot will be the death of this project.

**Comment by gingerbeardman** [comment]
@o1egl any chance you can merge/rebase this one? thanks!

**Comment by LucaFontanot** [comment]
@o1egl why is this closed

**Comment by gingerbeardman** [comment]
yeah this should not be closed

**Comment by khairul169** [comment]
It seems that this pull request has many merge conflicts. I've rebased and resolved them in this commit: c6139c4798c277241d4892969e1507f1da8b0d8e.
Also, thank you so much for this feature, @t924417424!

In case someone needs the Docker image: [khairul169/filebrowser:latest](https://hub.docker.com/r/khairul169/filebrowser)

**Pull request closed without merging**
