### PR TITLE
feat: Create user on proxy authentication if user does not exist

### LINKED ISSUE #3420: Automatically create account when using reverse proxy auth
**Is your feature request related to a problem? Please describe.**

[People are encountering a lot of troubles using the reverse proxy auth](https://github.com/filebrowser/filebrowser/issues/2100) as Filebrowser silently fails to handle usernames not matching any existing user

**Describe the solution you'd like**

Filebrowser should create a new account for these when needed

**Describe alternatives you've considered**

Listing and creating all users manually or automatically. Not good as it must be done periodically anyway

### PR DESCRIPTION
**Pull request by ahobsonsayers**
**Description**
When using proxy auth, if the proxy authenticates the user, but the user does not exist in File Browser, the user should be automatically created (with a random password, and lock password should naturally be false as the proxy is handling auth)

Fixes: #3420 #3292 #2515

- [x] DO make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your master!
- [x] DO make sure you are making a pull request against the **master branch** (left side). Also you should start *your branch* off *our master*.
- [x] DO make sure that File Browser can be successfully built. See [builds](https://github.com/filebrowser/community/blob/master/builds.md) and [development](https://github.com/filebrowser/community/blob/master/development.md).
- [x] AVOID breaking the continuous integration build.

### CODE REVIEW

**Comment by gaby** [comment]
@o1egl Any chance to get this merge. It would be very helpful for external auth.

**Comment by gaby** [comment]
@ahobsonsayers Your branch is out-of-date

**Comment by ahobsonsayers** [comment]
Thanks for merging @o1egl!

**Comment by melaniestnls** [comment]
Hello, @ahobsonsayers @o1egl 

Are we sure that the feature works in any case? Because I use the proxy method and when the user does not exist in filebrowser, I am stuck on the login page, but when it exists, the proxy method works fine I am automatically logged in.
For context, my filebrowser runs in a kubernetes configuration, and I do the SSO with Oauth2 as Proxy and Keycloak as IAM

Thank you for your help

**Comment by ahobsonsayers** [comment]
Hi @melaniestnls - I did test it when I made the PR, but if I am honest I haven't actually tested it since it got merged.

It is possible I made some changes after testing and before my eventual squashed commit, but I honestly cannot recall.

I might be able to test this again and look into fixing any bug I identify at some point soon, but I can't promise when this will be - sorry!

If you end up spotting or finding the problem in the meantime, please let me know!

**Comment by ahobsonsayers** [comment]
Ah, I just had another look at the code, and I think I have identified the issue - it's a silly one 🤦‍♀️

@melaniestnls if I make a new PR will you be able to test it? I sadly don't have an proxy setup anymore atm.

Thanks for notifying me of the issue!

**Comment by ahobsonsayers** [comment]
I think I have fixed this in #3666 - but i need to properly test

**Pull request merged**
