### PR TITLE
Allow to configure filebrowser through environment variables (#360) (#489)

### PR DESCRIPTION
**Pull request by maweck**
I also had the need to provide the settings as Environment variables. A quick research pointed out that Viper already supports the feature requested in #360 . So I did some tests and it works fine.

Not sure if you are fine with "FB" as a prefix or if you want to see this PR at all, because you may want to solve everything mentioned in #489 in one PR. However, at least I can let you guys know that it would work like this :)

Best regards

### CODE REVIEW

**Comment by eine** [comment]
@maweck thanks a lot!

Related to other enhancements in progress, flags/parameters with dots (#497) cannot be set through envvars. A replacement command is required. So, I already merged this commit into #506, and added the replacement there.

**Comment by eine** [comment]
@maweck this is now merged in master, along with other enhancements (#506). Please, let us know if you find any problem with it. Thanks again!

**Comment by maweck** [comment]
Looks very good! Thank you for the effort @1138-4EB - Do you have some kind of "pre-release" planned that can be tested?

**Comment by eine** [comment]
We'd like to have some PRs merged before publishing a new release (i.e. #494, #496, #515). However, there are two options for you to test it:

- Execute `USE_DOCKER="true" ./build/build_all.sh` in the root of the repo. A `filebrowser` binary will be generated.
- Use the latest docker image: `filebrowser/filebrowser:latest`.

In both cases you only need docker installed locally. So, alternatively, you can do it in play-with-docker.

See https://github.com/filebrowser/community/blob/master/development.md.

**Pull request closed without merging**
