### PR TITLE
Image resize improvements

### PR DESCRIPTION
**Pull request by o1egl**
- Limit number or image resize workers (#1039)
- Add cli param to disable image thumbnails (#1039)
- Cache resized images (#1033)

### CODE REVIEW

**Comment by ramiresviana** [comment]
I think the term img-resize in the cli params can cause confusion. Image resizing is related to the resize process applied on a image, that can be used with different goals. For example, image resize can be used to reduce disk and bandwidth usage or to have many sizes to display it in different screen sizes. I would suggest naming the params with thumbnail or preview words. Also i think the disable word should go first on "img-resize-disable", like "disable-thumbnail", for a more imperative description.

**Comment by alexisLefebvre** [comment]
Hello, how do you enable the cache? I put `"cache-dir": "/cache"` in my config, mounted a directory from the host to Docker, restarted filebrowser and the cache directory is always empty.

**Comment by niubility000** [comment]
> Hello, how do you enable the cache? I put `"cache-dir": "/cache"` in my config, mounted a directory from the host to Docker, restarted filebrowser and the cache directory is always empty.

me too.  I use a router as the server.

**Comment by o1egl** [comment]
@alexandrestein @niubility000 you should use --cache-dir cli param

**Comment by alexisLefebvre** [comment]
Thanks for the answer. How do we do it when using a docker-compose stack? I didn't found a way in the documentation.

**Comment by alexisLefebvre** [comment]
I found how to pass CLI parameters in https://github.com/filebrowser/filebrowser/issues/651#issuecomment-473935396

So we can use cache like this:

```yaml
version: '3.3'

services:
  filebrowser:
    image: filebrowser/filebrowser:v2
    restart: 'no'
    ports:
      - 127.0.0.1:80:80
    command: "--cache-dir=/cache"
    volumes:
      - "/home/me/:/srv/:ro"
      - "./data/database.db:/database.db"
      - "./data/.filebrowser.json:/.filebrowser.json"
      - "./data/cache:/cache"
```

**Pull request merged**
