### PR TITLE
fix: add overlay for sidebar on mobile

### LINKED ISSUE #3190: Mobile sidebar bug
**Description**
On mobile(android, chrome) "Opened sidebar" does not close when clicked outside of it

**Expected behaviour**
The sidebar closes 

**What is happening instead?**
Sidebar is not closed causing ugly visual bugs with selected item glitching on top of sidebar

**How to reproduce?**
On mobile, open sidebar, click outside of it on any item

This btw does not happen on my old local repo (before migration to vue 3.0)

### PR DESCRIPTION
**Pull request by kloon15**
**Description**
Fixes #3190 

:rotating_light: Before submitting your PR, please indicate which issues are either fixed or closed by this PR. See [GitHub Help: Closing issues using keywords](https://help.github.com/articles/closing-issues-via-commit-messages/).

- [x] DO make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your master!
- [x] DO make sure you are making a pull request against the **master branch** (left side). Also you should start *your branch* off *our master*.
- [x] DO make sure that File Browser can be successfully built. See [builds](https://github.com/filebrowser/community/blob/master/builds.md) and [development](https://github.com/filebrowser/community/blob/master/development.md).
- [x] AVOID breaking the continuous integration build.

### CODE REVIEW

**Comment by gdy666** [comment]
the overlay in frontend\src\components\header\HeaderBar.vue   Add a display condition “layoutStore.currentPromptName == 'sidebar'” 
Is it more appropriate?

**Comment by kloon15** [comment]
> the overlay in frontend\src\components\header\HeaderBar.vue Add a display condition “layoutStore.currentPromptName == 'sidebar'” Is it more appropriate?

True, I just dont like the gray look of the overlay there and i didnt wanna change the style:
image
I personally dont like the looks of this, everything just blends together with the same gray color.
Whats ur preference @o1egl ?

**Comment by o1egl** [comment]
> > the overlay in frontend\src\components\header\HeaderBar.vue Add a display condition “layoutStore.currentPromptName == 'sidebar'” Is it more appropriate?
> 
> True, I just dont like the gray look of the overlay there and i didnt wanna change the style: image I personally dont like the looks of this, everything just blends together with the same gray color. Whats ur preference @o1egl ?

I agree that it doesn't look good in the light theme. Do you have any ideas about how we can improve it?

**Comment by kloon15** [comment]
> > > the overlay in frontend\src\components\header\HeaderBar.vue Add a display condition “layoutStore.currentPromptName == 'sidebar'” Is it more appropriate?
> > 
> > 
> > True, I just dont like the gray look of the overlay there and i didnt wanna change the style: image I personally dont like the looks of this, everything just blends together with the same gray color. Whats ur preference @o1egl ?
> 
> I agree that it doesn't look good in the light theme. Do you have any ideas about how we can improve it?

Sure, ill test some ideas over weekend.

**Comment by o1egl** [comment]
> > > > the overlay in frontend\src\components\header\HeaderBar.vue Add a display condition “layoutStore.currentPromptName == 'sidebar'” Is it more appropriate?
> > > 
> > > 
> > > True, I just dont like the gray look of the overlay there and i didnt wanna change the style: image I personally dont like the looks of this, everything just blends together with the same gray color. Whats ur preference @o1egl ?
> > 
> > 
> > I agree that it doesn't look good in the light theme. Do you have any ideas about how we can improve it?
> 
> Sure, ill test some ideas over weekend.

Should I merge this one, or are you going to revisit it?

**Comment by kloon15** [comment]
> > > > > the overlay in frontend\src\components\header\HeaderBar.vue Add a display condition “layoutStore.currentPromptName == 'sidebar'” Is it more appropriate?
> > > > 
> > > > 
> > > > True, I just dont like the gray look of the overlay there and i didnt wanna change the style: image I personally dont like the looks of this, everything just blends together with the same gray color. Whats ur preference @o1egl ?
> > > 
> > > 
> > > I agree that it doesn't look good in the light theme. Do you have any ideas about how we can improve it?
> > 
> > 
> > Sure, ill test some ideas over weekend.
> 
> Should I merge this one, or are you going to revisit it?

Yes please, so at least we can close the related issue.

**Pull request merged**
