### PR TITLE
dep: use dep to manage vendor

### PR DESCRIPTION
**Pull request by Equim-chan**

### CODE REVIEW

**Comment by Equim-chan** [comment]
Hold on, there are some extra works to be done (build, docker, CI).

**Comment by Equim-chan** [comment]
Done now, ready for review.

**Comment by Equim-chan** [comment]
Done, ready for review.

**Review by hacdias — APPROVED** [review]

**Comment by hacdias** [comment]
Thanks @Equim-chan 😄

**Pull request merged**
