### PR TITLE
build: Update to node 22 and pnpm

### PR DESCRIPTION
**Pull request by kloon15**
This commit brings the project to support node 22 which became LTS and fixes broken builds with typescript 5.7+ until vue-tsc is updated and replaces npm with pnpm.

- Update tsconfig for node 22
- Pin typescript to 5.6.x to not break vue-tsc
- Replace npm with pnpm (corepack recommended)
- Fix some broken imports

- [x] DO make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your master!
- [x] DO make sure you are making a pull request against the **master branch** (left side). Also you should start *your branch* off *our master*.
- [x] DO make sure that File Browser can be successfully built. See [builds](https://github.com/filebrowser/community/blob/master/builds.md) and [development](https://github.com/filebrowser/community/blob/master/development.md).
- [x] AVOID breaking the continuous integration build.

Should be all good.

### CODE REVIEW

**Comment by o1egl** [comment]
@kloon15 thanks for the PR. Let's ensure that all the pipelines work before merging it to master

**Comment by kloon15** [comment]
> @kloon15 thanks for the PR. Let's ensure that all the pipelines work before merging it to master

Ofc, and i also forgot to update the Makefile. Workflows work fine now, its just vue-tsc being a blocker for now.

**Comment by kloon15** [comment]
I'll move typecheck to test-frontend since lint doesnt depend on it and it would stop eslint from running.

**Comment by kloon15** [comment]
@o1egl vue-tsc is pissing me off, i fixed 2 errors it reported and now i get these, and i cant find any directive to ignore them:
```
> vue-tsc -p ./tsconfig.app.json --noEmit

src/components/Shell.vue:1:1 - error TS9005: Declaration emit for this file requires using private name '(Anonymous function)'. An explicit type annotation may unblock declaration emit.

1 <template>
  ~

src/components/Shell.vue:1:1 - error TS9005: Declaration emit for this file requires using private name 'submit'. An explicit type annotation may unblock declaration emit.

1 <template>
  ~

src/components/prompts/Copy.vue:1:1 - error TS9005: Declaration emit for this file requires using private name 'copy'. An explicit type annotation may unblock declaration emit.

1 <template>
  ~

src/components/prompts/Delete.vue:1:1 - error TS9005: Declaration emit for this file requires using private name 'submit'. An explicit type annotation may unblock declaration emit.

1 <template>
  ~

src/components/prompts/FileList.vue:1:1 - error TS9005: Declaration emit for this file requires using private name 'select'. An explicit type annotation may unblock declaration emit.

1 <template>
  ~

src/components/prompts/Rename.vue:1:1 - error TS9005: Declaration emit for this file requires using private name 'submit'. An explicit type annotation may unblock declaration emit.

1 <template>
  ~

src/components/prompts/Share.vue:1:1 - error TS9005: Declaration emit for this file requires using private name 'deleteLink'. An explicit type annotation may unblock declaration emit.

1 <template>
  ~

src/components/prompts/Share.vue:1:1 - error TS9005: Declaration emit for this file requires using private name 'submit'. An explicit type annotation may unblock declaration emit.

1 <template>
  ~

src/components/prompts/UploadFiles.vue:1:1 - error TS9005: Declaration emit for this file requires using private name 'toggle'. An explicit type annotation may unblock declaration emit.

1 <template>
  ~


Found 9 errors in 7 files.

Errors  Files
     2  src/components/Shell.vue:1
     1  src/components/prompts/Copy.vue:1
     1  src/components/prompts/Delete.vue:1
     1  src/components/prompts/FileList.vue:1
     1  src/components/prompts/Rename.vue:1
     2  src/components/prompts/Share.vue:1
     1  src/components/prompts/UploadFiles.vue:1
 ELIFECYCLE  Command failed with exit code 2.
```

**Comment by kloon15** [comment]
@o1egl It should be good to merge. I can probably fix most eslint warnings in another PR.

**Pull request merged**
