### PR TITLE
fix: set preview mode as default for view-only users in MD files

### PR DESCRIPTION
**Pull request by ultwcz**
**Description**

fix a bug: set the preview mode as the default for only view access users

ref:
[Please explain the changes you made here.](https://github.com/filebrowser/filebrowser/issues/3461#issuecomment-2332232591)

:rotating_light: Before submitting your PR, please indicate which issues are either fixed or closed by this PR. See [GitHub Help: Closing issues using keywords](https://help.github.com/articles/closing-issues-via-commit-messages/).

- [x] DO make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your master!
- [x] DO make sure you are making a pull request against the **master branch** (left side). Also you should start *your branch* off *our master*.
- [x] DO make sure that File Browser can be successfully built. See [builds](https://github.com/filebrowser/community/blob/master/builds.md) and [development](https://github.com/filebrowser/community/blob/master/development.md).
- [x] AVOID breaking the continuous integration build.

**Further comments**

### CODE REVIEW

**Comment by baur** [comment]
Maybe rename:

**Set preview mode as default for view-only users in MD files**

**Comment by baur** [comment]
@o1egl, @hacdias, @Equim-chan, please merge this PR. I would like to use it in the user manuals

**Comment by hkclark** [comment]
@ultwcz This PR sounds like a great change to me.  Did you ever get any feedback on this?  Any idea if it's possible to resurrect it?  (I'm new to File Browser but loving it so far!)

**Comment by baur** [comment]
@hkclark

This feature has already been implemented in this fork.
https://github.com/gtsteffaniak/filebrowser

**Comment by hkclark** [comment]
> @hkclark
> 
> This feature has already been implemented in this fork. https://github.com/gtsteffaniak/filebrowser

@baur Wonderful!  Thank you very much!

**Pull request closed without merging**
