### PR TITLE
Add HEIF support

### PR DESCRIPTION
**Pull request by adrium**
**Description**

Add HEIF/HEIC support, a commonly used format with iPhones.

- [x] requesting to **pull a topic/feature/bugfix branch**
- [x] pull request against the **master branch**
- [x] File Browser can be successfully built **(amd64 and arm64 tested)**
- [x] no issues are opened in other repositories
- [x] continuous integration build passed

**Further comments**

This is an experimental change and may lead to more maintenance overhead than desired.
Anyway, I wanted to try it out and gather some feedback.

It builds successfully on `linux/amd64` and `linux/arm64`
It also builds on `darwin/amd64` with warnings.

It is able to read images 1-3 from https://github.com/tigranbs/test-heic-images but it segfaults for image 4.

Now the following questions arise:

1. Is it a generally embraced addition?
2. Is it possible to catch the SIGSEGV?
3. Should target architectures be conditionally included?

### CODE REVIEW

**Comment by jniggemann** [comment]
Would be a great feature to have!

**Comment by PLK2** [comment]
Here's my vote for HEIC support.

**Comment by pushpinderbal** [comment]
Would be a great feature to have in filebrowser.

**Comment by gaby** [comment]
👍🏻 for this feature!

**Comment by TCB13** [comment]
+1 on this feature, please merge.

**Comment by o1egl** [comment]
This feature adds a dependency on CGO. With that our existing release pipeline will be broken. It cannot be merged without rewriting the build pipeline to support CGO cross-compilation.

**Pull request closed without merging**
