### PR TITLE
Rename manager to browser

### PR DESCRIPTION
**Pull request by eine**
Just replace remaining ocurrences of `Manager` to `Browser`, and `fm` to `fb`.

### CODE REVIEW

**Comment by hacdias** [comment]
@1138-4EB did you keep the LF line endings? It seems to have changed the whole file.

**Comment by eine** [comment]
I am using a windows box, but git should automatically handle it. Indeed, I am trying to change it, but as soon as I `git add` the files with LF line endings, they are changed and nothing is staged.

---

Note that this only happens with markdown files, not with go sources. However, I used the same machine/context to submit both commits. Furthermore, with `--ignore-space-change` differences are properly shown.

**Comment by eine** [comment]
@hacdias, I think that these markdown files have CRLF line endings, and I changed them to LF. This is the commit that changed previous LF endings to CRLF (oct 30): https://github.com/filebrowser/filebrowser/commit/99c8c92c6c6d1225380dbbfc5b61d4263a129156#diff-04c6e90faac2675aa89e2176d2eec7d8

**Comment by hacdias** [comment]
Thank you @1138-4EB! 😄

**Pull request merged**
