### PR TITLE
New Setting: Disable used percentage

### PR DESCRIPTION
**Pull request by AlencarGabriel**
**Description**

:rotating_light: Before submitting your PR, please read [community](https://github.com/filebrowser/community), and indicate which issues (in any of the repos) are either fixed or closed by this PR. See [GitHub Help: Closing issues using keywords](https://help.github.com/articles/closing-issues-via-commit-messages/).

- [x] DO make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your master!
- [x] DO make sure you are making a pull request against the **master branch** (left side). Also you should start *your branch* off *our master*.
- [x] DO make sure that File Browser can be successfully built. See [builds](https://github.com/filebrowser/community/blob/master/builds.md) and [development](https://github.com/filebrowser/community/blob/master/development.md).
- [x] DO make sure that related issues are opened in other repositories. I.e., the frontend, caddy plugins or the web page need to be updated accordingly.
- [x] AVOID breaking the continuous integration build.

**Further comments**

Hi! I propose this PR to meet a need that we had and could be useful to the community.

Hiding the disk usage percentage graph was necessary to omit the total size of an NFS volume in Kubernetes, which could be misinterpreted or misused by users.

I built the new configuration entirely based on the existing `branding.disableExternal`.

I remain at your disposal for further clarifications, and I await its approval and publication.

### CODE REVIEW

**Comment by AlencarGabriel** [comment]
Hi @o1egl , any news for this PR?

**Comment by AlencarGabriel** [comment]
Interested in this PR?

**Comment by zoidy** [comment]
I'd like to see this merged. Perhaps also create a PR in the documentation repo to document this new functionality?

**Comment by AlencarGabriel** [comment]
Interested in this PR?

**Comment by AlencarGabriel** [comment]
@o1egl , @hacdias , @Equim-chan ?

**Comment by AlencarGabriel** [comment]
Could @o1egl have a look, please? At least one positive or negative return?

**Comment by AlencarGabriel** [comment]
Please @hacdias / @o1egl / @ramiresviana  , any feedback? Several issues and PRs being closed, and this one without any feedback

**Comment by zoidy** [comment]
> Please @hacdias / @o1egl / @ramiresviana , any feedback? Several issues and PRs being closed, and this one without any feedback

It seems like devs are probably too busy with other things to look at new features, evidenced by the fact that many recent merges are just tiny bug fixes or translation updates (a response of any kind would be helpful though). While I would have liked to have your feature merged, perhaps it's time to maintain your own fork with your own features and just pull from upstream when needed.

**Review by o1egl — CHANGES_REQUESTED** [review]
Could you please resolve the merge conflicts and fix the linting errors?

**Comment by AlencarGabriel** [comment]
@o1egl conflicts and linting erros fixed.

**Comment by AlencarGabriel** [comment]
@o1egl I didn't know the commit policy when I opened the PR. Do I need to rewrite all commits to proceed with the merge?

**Review by o1egl — CHANGES_REQUESTED** [review]
When display usage is disabled, the API request is still sent to the server. I think we shouldn't do this

**Comment by AlencarGabriel** [comment]
> When display usage is disabled, the API request is still sent to the server. I think we shouldn't do this

@o1egl , I maked rebase for fix lint-commits, and fixed request API when config is disabled.

**Comment by AlencarGabriel** [comment]
Thanks @o1egl  for this approval! I'm happy to have contributed to this project.

**Pull request merged**
