### PR TITLE
Add folder upload

### PR DESCRIPTION
**Pull request by ramiresviana**
**Description**
Implements ability to upload folders via drag and drop.

**Further comments**
Uses DataTransferItem.webkitGetAsEntry() to recursively retrieve data from directories, allows multiple selection with files and directories. Works with modern browsers, fallback to old DataTransfer API when not compatible.

### CODE REVIEW

**Comment by o1egl** [comment]
@ramiresviana thank you for your PR. Could you please fix build errors?

**Comment by ramiresviana** [comment]
@o1egl fixed build errors.

**Comment by o1egl** [comment]
@ramiresviana great job. Can you please add support of upload button too?

**Comment by ramiresviana** [comment]
@o1egl is not possible to make an input that accepts both files and folders. What can be made is add another button in the header that only allows selecting folders for upload.

**Comment by o1egl** [comment]
@ramiresviana do you have an idea how to display it? Maybe we can display a popup with 2 file/filder options if browser supports it.

**Comment by ramiresviana** [comment]
@o1egl i can make an prompt that opens when the user clicks on upload button, like this:
image

**Comment by o1egl** [comment]
@ramiresviana that would be perfect! But let’s add browser compatibility check and display it only for supported ones.

**Comment by ramiresviana** [comment]
- Added upload prompt: shows when header upload button is clicked. When browser does not support webkitGetAsEntry for folder upload, file picker window will be showed without prompt.
- Empty folder upload: allows uploading empty folder structure. Works only with drag and drop, because form file input does not return empty folders.

@o1egl the buttons in the upload prompt are responsive and can be reused in other components if needed.

**Comment by o1egl** [comment]
@ramiresviana awesome job!

**Pull request merged**
