### PR TITLE
add SRT subtitles support for videos

### PR DESCRIPTION
**Pull request by glowinthedark**
**Description**
- Add support for SRT subtitles for videos in [files/file.go:299](https://github.com/filebrowser/filebrowser/pull/2592/files#diff-867e1d86c2982475de237361ac472005be64af1d305072643337e63ed5c72ba1R301)
- replace `afero.ReadDir()` with `afero.Walk()` to also search for `vtt/srt` subtitles in folders like `(Subtitles|Subs|subtitles|sub)`
- in [Preview.vue](https://github.com/filebrowser/filebrowser/pull/2592/files#diff-a8ee9ee497925a6f859b8ba12826e1e5c405f1b39b628140a44421044030c10b) replace the SRT <track> element with a binary Blob object containing subtitles converted to VTT.

> converted SRT to WebVTT subtitles successfully validate against the w3c validator at https://w3c.github.io/webvtt.js/parser.html (with the SRT files I had at hand)

##### Sample input SRT
```srt
1
00:00:54,320 --> 00:00:55,480
<font color="#ffffff">若干天前</font><br><font color="#00ffff">ruò gān tiān qián</font><br>[English subtitles are available]<br>[A few days ago,]

2
00:00:56,160 --> 00:00:57,600
<font color="#ffffff">发生了一些怪事</font><br><font color="#d663fd">發生了一些怪事</font><br><font color="#00ffff">fā shēng le yī xiē guài shì</font><br>[some strange things happened.]

3
00:00:58,920 --> 00:01:01,240
<font color="#ffffff">这是我们抵达附近村镇时听说的</font><br><font color="#d663fd">這是我們抵達附近村鎮時聽說的</font><br><font color="#00ffff">zhè shì wǒ men dǐ dá fù jìn cūn zhèn shí tīng shuō de</font><br>[We heard about it when we arrived
at a nearby town's village.]
```

##### Sample converted VTT 
_(set on the video subtitle track via `URL.createObjectURL(Blob)`):_

```webvtt
WEBVTT

STYLE
::cue {color: #ffc800; border: 2px solid black; font-size: 3vh;}
::cue(b) {color: rgb(51, 216, 18); border: 2px solid black;}
::cue(i) {color: #00bafd;}
::cue(u) {color: #ff00ee;}
::cue(.c_ffffff) {color: #ffffff;}
::cue(.c_00ffff) {color: #00ffff;}
::cue(.c_d663fd) {color: #d663fd;}

1
00:00:54.320 --> 00:00:55.480
<c.c_ffffff>若干天前</c>
<c.c_00ffff>ruò gān tiān qián</c>
[English subtitles are available]
[A few days ago,]

2
00:00:56.160 --> 00:00:57.600
<c.c_ffffff>发生了一些怪事</c>
<c.c_d663fd>發生了一些怪事</c>
<c.c_00ffff>fā shēng le yī xiē guài shì</c>
[some strange things happened.]

3
00:00:58.920 --> 00:01:01.240
<c.c_ffffff>这是我们抵达附近村镇时听说的</c>
<c.c_d663fd>這是我們抵達附近村鎮時聽說的</c>
<c.c_00ffff>zhè shì wǒ men dǐ dá fù jìn cūn zhèn shí tīng shuō de</c>
[We heard about it when we arrived
at a nearby town's village.]
```

### CODE REVIEW

**Comment by maeryo** [comment]
Your code works perfectly.👍
I hope the reviewer will quickly approve this code.

**Comment by kloon15** [comment]
@glowinthedark Great work u did, i made some improvements to ur code just as reading subtitles from Subs folder and optimized the loading of them. How can i contribute without opening a new PR?

**Comment by glowinthedark** [comment]
@kloon15: reading from a subfolder like `subs` would be the golang side which I barely touched apart from including `.srt` so that change would be transparent for this pr. also, it would probably make sense to check for `subs` for vtt subtitles too, so that would be in a different scope and can be handled independently.
as an alternative, pass me the reference to your branch with changes and I'll see if that can be easily integrated into this one

**Comment by kloon15** [comment]
> @maeryo: reading from a subfolder like `subs` would be the golang side which I barely touched apart from including `.srt` so that change would be transparent for this pr. also, it would probably make sense to check for `subs` for vtt subtitles too, so that would be in a different scope and can be handled independently. as an alternative, pass me the reference to your branch with changes and I'll see if that can be easily integrated into this one

See: https://github.com/filebrowser/filebrowser/commit/ab7759482cc11a0e1740a1a5000cc0fecf4410fa

**Comment by glowinthedark** [comment]
@kloon15: tested and updated the PR with your changes on the JS side, much cleaner now 😅 thank you so much! 👍  

as for the go side maybe it would make more sense to address it in a separate PR, wdyt? as it stands now there is duplication of code at lines [301](https://github.com/filebrowser/filebrowser/blob/ab7759482cc11a0e1740a1a5000cc0fecf4410fa/files/file.go#L301) and [311](https://github.com/filebrowser/filebrowser/blob/ab7759482cc11a0e1740a1a5000cc0fecf4410fa/files/file.go#L311) and [320](); also `"Subs"` would be a hard case-sensitive folder name on non-windows OS's, and that would probably better be configurable, for example VLC ootb uses `./Subtitles, ./subtitles, ./Subs, ./subs` in its GUI config. 

One possible quick way without having to extract it to the config screen could be eg looping over `filepath.Glob(“[S|s]ub[s|titles]”)` or something along these lines, wdyt?

**Comment by kloon15** [comment]
> @kloon15: tested and updated the PR with your changes on the JS side, much cleaner now 😅 thank you so much! 👍
> 
> as for the go side maybe it would make more sense to address it in a separate PR, wdyt? as it stands now there is duplication of code at lines [301](https://github.com/filebrowser/filebrowser/blob/ab7759482cc11a0e1740a1a5000cc0fecf4410fa/files/file.go#L301) and [311](https://github.com/filebrowser/filebrowser/blob/ab7759482cc11a0e1740a1a5000cc0fecf4410fa/files/file.go#L311) and 320; also `"Subs"` would be a hard case-sensitive folder name on non-windows OS's, and that would probably better be configurable, for example VLC ootb uses `./Subtitles, ./subtitles, ./Subs, ./subs` in its GUI config.
> 
> One possible quick way without having to extract it to the config screen could be eg looping over `filepath.Glob(“[S|s]ub[s|titles]”)` or something along these lines, wdyt?

For sure, that sounds much better, i know nothing about Go so i just quickly put it together for my needs.

**Comment by glowinthedark** [comment]
@kloon15: simplified the go side to use `afero.Walk()` with a custom walker predicate instead of the original `afero.ReadDir()` which was reading everything from the folder and then filtering the results; now `Subs/Subtitles/subs/subtitles` are searched as well and non-matching subfolders skipped

**Comment by kloon15** [comment]
@glowinthedark Do u think ur included VTT styles could somehow be customized? I for one do not want different colors for different font styles, and i believe for most ppl the default styles are perfectly fine.

**Comment by glowinthedark** [comment]
@kloon15: 
> Do u think ur included VTT styles could somehow be customized? 

I guess the VTT subtitle styling could be extracted to the GUI settings but the question is how much a feature like this is actually needed and would be actually used by end users, and would time and effort spent on this actually bring any value? 

Most SRT subtitles out there (probably more than 99.99%) do not have any styling (`<font color..>` is the only way that I know which is supported in SRT), so the current style is white color with black outlines which imo is a reasonable default.

Moreover, this PR is specifically about SRT support as such, and not about SRT styling. I've added parsing for `<font color..>` because I generate my own SRT subtitles in multiple languages and writing systems, so it is my personal use case to be able to visually differentiate fragments based on colors. For other users who use regular SRT files without styling that's transparent, although it is still to be found out how much there is a need for customizing the size, font family, outline thickness, etc. Ideally, it would be great if more people would comment on this aspect with their real-life use cases so that a reasonable approach can be defined.

**Comment by kloon15** [comment]
> @kloon15:
> 
> > Do u think ur included VTT styles could somehow be customized?
> 
> I guess the VTT subtitle styling could be extracted to the GUI settings but the question is how much a feature like this is actually needed and would be actually used by end users, and would time and effort spent on this actually bring any value?
> 
> Most SRT subtitles out there (probably more than 99.99%) do not have any styling (`<font color..>` is the only way that I know which is supported in SRT), so the current style is white color with black outlines which imo is a reasonable default.
> 
> Moreover, this PR is specifically about SRT support as such, and not about SRT styling. I've added parsing for `<font color..>` because I generate my own SRT subtitles in multiple languages and writing systems, so it is my personal use case to be able to visually differentiate fragments based on colors. For other users who use regular SRT files without styling that's transparent, although it is still to be found out how much there is a need for customizing the size, font family, outline thickness, etc. Ideally, it would be great if more people would comment on this aspect with their real-life use cases so that a reasonable approach can be defined.

So are these colored styles just for testing?
```
::cue(b) {color: rgb(51, 216, 18); border: 2px solid black;}
::cue(i) {color: #00bafd;}
::cue(u) {color: #ff00ee;}
```

**Comment by glowinthedark** [comment]
> So are these colored styles just for testing?

@kloon15: those styles are some default values as a starting point; these are the only 3 styles that VTT supports apart from css class styles; nothing else is supported; so they are there in order to make it clear for anyone who needs/wants to make something useful with them; as they stand they will provide visual emphasis in the browser; and users who want to customize them can have a starting point

**Comment by glowinthedark** [comment]
@gdy666: you recently did the optimization for #2637 — could you please share the approach you used to measure the subtitle detection performance so that I can try to reproduce and see if the new traversal approach is slower or not? I would like to know if the approach in this pr is slower compared to your optimization and if it is then I will revert to the code that's currently in master.

**Comment by gdy666** [comment]
> @gdy666: you recently did the optimization for #2637 — could you please share the approach you used to measure the subtitle detection performance so that I can try to reproduce and see if the new traversal approach is slower or not? I would like to know if the approach in this pr is slower compared to your optimization and if it is then I will revert to the code that's currently in master.

My modification is quite simple, and you can understand it by briefly reviewing the code. It primarily involves reducing the repetitive reading of the parent directory.

**Comment by glowinthedark** [comment]
@kloon15: now that this is closed I want to thank you once again for your contribution on the js code — I learned quite a bit from your fork; also for my use case filebrowser does more than I need, and [caddy](https://github.com/caddyserver/caddy/) in fact fills all my needs with the [custom file_server template](https://github.com/glowinthedark/caddy-file-server-browse-extension) where I have incorporated the async improvements you have made.

**Comment by kloon15** [comment]
> @kloon15: now that this is closed I want to thank you once again for your contribution on the js code — I learned quite a bit from your fork; also for my use case filebrowser does more than I need, and [caddy](https://github.com/caddyserver/caddy/) in fact fills all my needs with the [custom file_server template](https://github.com/glowinthedark/caddy-file-server-browse-extension) where I have incorporated the async improvements you have made.

Sure, np!

**Pull request closed without merging**
